# Generated by Django 2.1.7 on 2019-03-29 04:48

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190329_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('product.create', 'On Product Create'), ('product.update', 'On Product Update')], max_length=100)),
                ('endpoint', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
