# Generated by Django 2.1.7 on 2019-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='productupload',
            name='products_file',
            field=models.CharField(max_length=250),
        ),
    ]
